### ISSUE TITLE
Doctrine 1.2 API documentation

### ISSUE THREAD

**Issue by romangetman** [doctrine/doctrine1#53]
I can't seem to find the API documentation anywhere. Could you please host it somewhere or point me there, if it's online.

**Comment by mstralka** [comment]
I know this is an old question but the docs are also here:
http://doctrine.readthedocs.org/en/latest/en/

**Comment by mstralka** [comment]
And it's also still here:
http://docs.doctrine-project.org/projects/doctrine1/en/latest/en/
