### ISSUE TITLE
Doctrine fix for PHP 7.0.0

### ISSUE THREAD

**Issue by dragonofmercy** [doctrine/doctrine1#69]
Hi team,
Here is some correction for PHP 7.0.0:

Doctrine/Collection.php - line 463

``` php
- $record->$relation['alias'] = $this->reference;
+ $record->{$relation['alias']} = $this->reference;
```

Doctrine/Query/Abstract.php - line 1122

``` php
- $record->$callback['callback']($event);
- $table->getRecordListener()->$callback['callback']($event);
+ $record->{$callback['callback']($event)};
+ $table->getRecordListener()->{$callback['callback']($event)};
```

**Comment by andreasbernhard** [comment]
Thank you! I've forked this and just made it PHP 7.0 compatible (only changes) right here: https://github.com/bsinfosys/doctrine1

**Comment by aripringle** [comment]
Thanks for the tips. We've implemented this in a repo that we've been maintaining, along with several other changes to get the test suite to run under PHP7: https://github.com/diablomedia/doctrine1

**Comment by immwi** [comment]
Thanks! This helped us a lot!

**Comment by aureality** [comment]
Thanks a lot! This saved me from migrating to Doctrine 2 or another ORM for a 7 year old project ....
