### ISSUE TITLE
Doctrine 1 JIRA not migrated

### ISSUE THREAD

**Issue by falkenhawk** [doctrine/doctrine1#71]
It's a shame that Doctrine 1 JIRA issues have not beed migrated to github. Some people are still using Doctrine 1 and have no chance to migrate to 2.
e.g. I wanted to get some info about the bug I reported several years ago, as I encoutered it again: http://webcache.googleusercontent.com/search?q=cache:KpYEn6DJfp8J:www.doctrine-project.org/jira/browse/DC-313%3Fpage%3Dcom.atlassian.jira.plugin.system.issuetabpanels:changehistory-tabpanel+&cd=1&hl=pl&ct=clnk&gl=pl

It's only a matter of short time when that will be gone for good, also from google.

**Comment by mishal** [comment]
+1

We would like to have Doctrine1 issues back too. We have still Doctrine1 based apps to be maintained.
I don't know if its still possible, maybe @beberlei can say?

**Comment by marcing** [comment]
+1

I am also still using Doctrine 1, the system is so big it is not possible to migrate to Doctrine 2.
Lack of support from author was really a big problem for me over the years. Now JIRA is also gone, which makes it even worse.

**Comment by mh-ovos** [comment]
http://www.doctrine-project.org/jira/browse/DC-815 is not saved anywhere. Neither on archive.org nor google cache. If you can't migrate doctrine1 issues to github, maybe you could provide us e.g. a database dump from jira or exported static pages. Pretty please?

**Comment by mh-ovos** [comment]
Hello?
