### ISSUE TITLE
MySQL 5.7+ error on DISTINCT subquery execution

### ISSUE THREAD

**Issue by Axinet** [doctrine/doctrine1#79]
If someone else also hit the problem with MySQL 5.7+

> Expression #1 of ORDER BY clause is not in SELECT list,

There is a easy fix by adding 'mysql' driver name (last OR below, originally is missing) to the Query.php file at line 1417 (as now MySQL also require order by fields to be preserved in select clause):
`// pgsql & oracle need the order by fields to be preserved in select clause
        if ($driverName == 'pgsql' || $driverName == 'oracle' || $driverName == 'oci' || $driverName == 'mssql' || $driverName == 'odbc' || $driverName = 'mysql') {`

**Comment by alcaeus** [comment]
> There is a easy fix by...
by not using software that’s horribly outdated. Please don’t use Doctrine 1 anymore, period.
